// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAvg25Ihq5jpRovtWUo4KR4aDxBujOp2lA',
    appId: '1:480690148394:web:b6e4a2bc0f35e81e415f53',
    messagingSenderId: '480690148394',
    projectId: 'raja-shivchhatrapati-parivar',
    authDomain: 'raja-shivchhatrapati-parivar.firebaseapp.com',
    databaseURL: 'https://raja-shivchhatrapati-parivar-default-rtdb.firebaseio.com',
    storageBucket: 'raja-shivchhatrapati-parivar.firebasestorage.app',
    measurementId: 'G-E8HHTR0QEF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyClroJrPCaLpuVEF-UgamsrU2IA1lxdEYM',
    appId: '1:480690148394:android:5c3f4d894e1f419d415f53',
    messagingSenderId: '480690148394',
    projectId: 'raja-shivchhatrapati-parivar',
    databaseURL: 'https://raja-shivchhatrapati-parivar-default-rtdb.firebaseio.com',
    storageBucket: 'raja-shivchhatrapati-parivar.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBOozJkQmLJR1K-esQ4UqHMe9-WcsIx_K0',
    appId: '1:480690148394:ios:1f59e8db3a356f2b415f53',
    messagingSenderId: '480690148394',
    projectId: 'raja-shivchhatrapati-parivar',
    databaseURL: 'https://raja-shivchhatrapati-parivar-default-rtdb.firebaseio.com',
    storageBucket: 'raja-shivchhatrapati-parivar.firebasestorage.app',
    iosBundleId: 'com.example.rajaShivchhatrapatiParivar',
  );
  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBOozJkQmLJR1K-esQ4UqHMe9-WcsIx_K0',
    appId: '1:480690148394:ios:1f59e8db3a356f2b415f53',
    messagingSenderId: '480690148394',
    projectId: 'raja-shivchhatrapati-parivar',
    databaseURL: 'https://raja-shivchhatrapati-parivar-default-rtdb.firebaseio.com',
    storageBucket: 'raja-shivchhatrapati-parivar.firebasestorage.app',
    iosBundleId: 'com.example.rajaShivchhatrapatiParivar',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAvg25Ihq5jpRovtWUo4KR4aDxBujOp2lA',
    appId: '1:480690148394:web:5aa3bcbcfb751438415f53',
    messagingSenderId: '480690148394',
    projectId: 'raja-shivchhatrapati-parivar',
    authDomain: 'raja-shivchhatrapati-parivar.firebaseapp.com',
    databaseURL: 'https://raja-shivchhatrapati-parivar-default-rtdb.firebaseio.com',
    storageBucket: 'raja-shivchhatrapati-parivar.firebasestorage.app',
    measurementId: 'G-HQ5D6KM97M',
  );
}
